FunApp.Web/Areas/Admin/Controllers/JokesController.cs
namespace FunApp.Web.Areas.Admin.Controllers
{
    using Data;
    using Data.Models;
    using Services.Interfaces;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;
    using System.Threading.Tasks;

    [Area("Admin")]
    public class JokesController : Controller
    {
        private readonly FunAppDbContext context;
        private readonly IJokeService service;

        public JokesController(FunAppDbContext context, IJokeService service)
        {
            this.context = context;
            this.service = service;
        }

        public async Task<IActionResult> All()
        {
            var result = await this.service.All();

            return this.View(result);
        }

        // GET: Admin/Jokes
        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            var result = await this.context.Jokes.ToListAsync();
            return View(result);
        }

        // GET: Admin/Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await this.context.Jokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // GET: Admin/Jokes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Jokes/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Likes")] Joke joke)
        {
            if (ModelState.IsValid)
            {
                this.context.Add(joke);
                await this.context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Admin/Jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await this.context.Jokes.FindAsync(id);
            if (joke == null)
            {
                return NotFound();
            }
            return View(joke);
        }

        // POST: Admin/Jokes/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Likes")] Joke joke)
        {
            if (id != joke.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.context.Update(joke);
                    await this.context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeExists(joke.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Admin/Jokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await this.context.Jokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // POST: Admin/Jokes/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var joke = await this.context.Jokes.FindAsync(id);
            this.context.Jokes.Remove(joke);
            await this.context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeExists(int id)
        {
            return this.context.Jokes.Any(e => e.Id == id);
        }
    }
}

FunApp.Web/Controllers/CategoriesController.cs
namespace FunApp.Web.Controllers
{
    using Extentions;
    using Models.Category;
    using Services.Interfaces;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using System;

    [Authorize(Roles = GlobalConstants.AdministratorRole)]
    public class CategoriesController : Controller
    {
        private const int PageSize = 15;

        private readonly ICategoryService service;

        public CategoriesController(ICategoryService service)
        {
            this.service = service;
        }

        public IActionResult All(int page = 1)
        => View(new CategoryPageListingModel
        {
            CurrentPage = page,
            Categories = this.service.All(page, PageSize),
            TotalPage = (int)Math.Ceiling(this.service.Total() / (double)PageSize)
        });

        [Route("categories/stylesbycategory/{categoryId}")]
        public IActionResult StylesByCategory(int categoryId)
        {
            var styles = this.service.StylesByCategory(categoryId);

            if (styles == null)
            {
                return NotFound();
            }

            return View(styles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(BasicCategoryModel model)
        {
            this.service.Create(model.Title, model.ThumbnailImagePath);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        [Route("categories/edit/{id}")]
        public IActionResult Edit(int id)
        {
            var customer = this.service.FindById(id);

            if (customer == null)
            {
                return NotFound();
            }

            return View(new BasicCategoryModel
            {
                Id = id,
                Title = customer.Title,
                ThumbnailImagePath = customer.ThumbnailImagePath
            });
        }

        [HttpPost]
        [Route("categories/edit/{id}")]
        public IActionResult Edit(int id, CategoryModel categoryModel)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryModel);
            }

            var categoryExist = this.service.CategoryExist(id);

            if (categoryExist == false)
            {
                return NotFound();
            }

            this.service
                .Edit(id, categoryModel.Title, categoryModel.ThumbnailImagePath);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Delete(int id)
        {
            return this.View(id);
        }

        public IActionResult Destroy(int id)
        {
            this.service.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

FunApp.Web/Controllers/StylesController.cs
namespace FunApp.Web.Controllers
{
    using Extentions;
    using Models.Style;
    using Services.Interfaces;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Authorization;
    using System.Linq;
    using System.Collections.Generic;

    [Authorize(Roles = GlobalConstants.AdministratorRole)]
    public class StylesController : Controller
    {
        private readonly IStyleService styles;
        private readonly ICategoryService categories;

        public StylesController(IStyleService styles, ICategoryService categories)
        {
            this.styles = styles;
            this.categories = categories;
        }

        public IActionResult All()
        => View(new Styles
        {
            AllStyles = this.styles.All()
        });

        public IActionResult ById(int categoryId)
        {
            var category = this.styles.ById(categoryId);

            if (category == null)
            {
                return NotFound();
            }

            return View(new Styles
            {
                CategoryId = categoryId,
                AllStyles = category
            });
        }

        private IEnumerable<SelectListItem> GetCategoriesListItem()
        {
            return this.categories
                .All()
                .Select(c => new SelectListItem
                {
                    Text = c.Title,
                    Value = c.Id.ToString()
                });
        }

        public IActionResult Create() => View(new Styles
        {
            Categories = this.GetCategoriesListItem()
        });

        [HttpPost]
        public IActionResult Create(Styles model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = this.GetCategoriesListItem();
                return View(model);
            }

            this.styles.Create(model.Id, model.Title, model.CategoryId);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Edit(int id)
        {
            var style = this.styles.FindById(id);

            if (style == null)
            {
                return NotFound();
            }

            return View(new StyleEditModel
            {
                Id = id,
                Title = style.Title,
                CategoryId = style.CategoryId,
                IsEdit = true
            });
        }

        [HttpPost]
        public IActionResult Edit(int id, StyleEditModel model)
        {
            if (!ModelState.IsValid)
            {
                model.IsEdit = true;
                return View(model);
            }

            this.styles.Edit(id, model.Title);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Delete(int id)
        {
            return this.View(id);
        }

        public IActionResult Destroy(int id)
        {
            this.styles.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

FunApp.Web/Controllers/UsersController.cs
namespace FunApp.Web.Controllers
{
    using Extentions;
    using Data;
    using Data.Models;
    using Models.User;
    using Services.Interfaces;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Authorization;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.EntityFrameworkCore;
    using System;

    [Authorize(Roles = GlobalConstants.AdministratorRole)]
    public class UsersController : Controller
    {
        private readonly IAdminUserService users;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly FunAppDbContext db;

        public UsersController(IAdminUserService users,
                               UserManager<User> userManager,
                               RoleManager<IdentityRole> roles,
                               SignInManager<User> signInManager,
                               FunAppDbContext db)
        {
            this.users = users;
            this.roleManager = roles;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.db = db;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            model.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await this.signInManager.PasswordSignInAsync(model.Email,
                                                                          model.Password,
                                                                          model.RememberMe,
                                                                          lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    model.LoginInValid = "";
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt");
                }
            }

            return PartialView("_UserLoginPartial", model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout(string retunrUrl = null)
        {
            await this.signInManager.SignOutAsync();

            if (retunrUrl == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return LocalRedirect(retunrUrl);
            }
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationModel model)
        {
            model.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                var user = new User
                {
                    UserName = model.Email,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNumber,
                    FirstName = model.FirstName,
                    LastName = model.LastName
                };

                var result = await this.userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    model.RegistrationInValid = "";

                    await this.signInManager.SignInAsync(user, isPersistent: false);

                    return RedirectToAction("Index", "Home");
                }

                AddErrorsToModelState(result);
            }

            return PartialView("_UserRegistrationPartial", model);
        }

        public IActionResult Index()
        {
            var allUsers = this.users.All();
            var allRoles = this.roleManager
                .Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
                .ToList();

            return View(new AdminUsersViewModel
            {
                Users = allUsers,
                Roles = allRoles
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddToRole(AddUserToRoleFormModel modell)
        {
            var roleExists = await this.roleManager.RoleExistsAsync(modell.Role);
            var user = await this.userManager.FindByIdAsync(modell.UserId);
            var userExists = user != null;

            if (!roleExists || !userExists)
            {
                ModelState.AddModelError(string.Empty, "Invalid Identity details.");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AllListing));
            }

            await this.userManager.AddToRoleAsync(user, modell.Role);

            TempData.AddSuccessMessage($"User {user.UserName} successfully added to the {modell.Role} role.");

            return RedirectToAction(nameof(AllListing));
        }

        [AllowAnonymous]
        public async Task<bool> UserNameExists(string userName)
        {
            bool userNameExists = await this.db.Users
                .AnyAsync(u => u.UserName.ToUpper() == userName.ToUpper());

            if (userNameExists)
            {
                return true;
            }
            return false;
        }

        private void AddErrorsToModelState(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }

        public IActionResult AllListing(int page = 1, int pageSize = 15)
        {
            var allUsers = this.users.AllListings(page, pageSize);
            var allRoles = this.roleManager
                .Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
                .ToList();

            return View(new UsersPageListingModel
            {
                CurrentPage = page,
                TotalPage = (int)Math.Ceiling(this.users.Total() / (double)pageSize),
                AllUsers = allUsers,
                Roles = allRoles
            });
        }
    }
}

FunApp.Web/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using FunApp.Web.Extentions

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, GlobalConstants.AdministratorRole))
@*@if(User.IsInRole(GlobalConstants.AdministratorRole))*@
{
<li class="nav-item dropdown show">
        @*Менюто Admin се разминава с останалите менюта. На долния ред е оправено.
        <a class="btn dropdown-toggle" href="#" data-toggle="dropdown">Admin</a>*@
    <a class="dropdown-toggle nav-link text-dark" href="#" data-toggle="dropdown">Admin</a>
    <div class="dropdown-menu">
        <a class="dropdown-item" asp-controller="Categories" asp-action="All">Category</a>
        <a class="dropdown-item" asp-controller="Styles" asp-action="All">Style</a>
        @*Може да се постави underline(черта под някой ред на dropdown-menu-то)
        <div class="dropdown-divider"></div>*@
        <a class="dropdown-item" href="#">Song</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" asp-area="Admin" asp-controller="Jokes" asp-action="Index">Jokes</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" asp-controller="Users" asp-action="Index">Users</a>
    </div>
</li>
}

FunApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FunApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FunApp.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_AdminMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FunApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FunApp.Web/Views/Shared/_UserLoginPartial.cshtml
@model LoginModel

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_login">
                <form id="UserLoginForm" asp-controller="Users" asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LoginInValid" />
                    <div class="form-group row">
                        <label asp-for="Email" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Email" placeholder="Email Address" class="form-control" />
                        </div>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Password" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" placeholder="Password" class="form-control" />
                        </div>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-8 offset-md-4">
                            <div class="form-check">
                                <input asp-for="RememberMe" class="form-check-input" />
                                <label asp-for="RememberMe" class="form-check-label"></label>
                                <span asp-validation-for="RememberMe" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" id="login" name="login" class="btn btn-primary">Login</button>
        </div>
    </div>
</div>

FunApp.Web/Views/Shared/_UserRegistrationPartial.cshtml
@model RegistrationModel

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_register">
                <form id="UserRegistrationForm" name="UserRegistrationForm" asp-controller="Users" asp-action="Register">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="RegistrationInValid">
                    <div class="form-group row">
                        <label asp-for="Email" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Email" placeholder="Email Address" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Password" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" placeholder="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="ConfirmPassword" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FirstName" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="FirstName" placeholder="First Name" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="LastName" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="LastName" placeholder="Last Name" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="PhoneNumber" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="PhoneNumber" placeholder="Phone Number" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <div class="form-check">
                                <input asp-for="AcceptUserAgreement" class="form-check-input" />
                                <label asp-for="AcceptUserAgreement" class="form-check-label">I accept the <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a></label>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button id="register" name="register" type="button" class="btn btn-primary">Register</button>
        </div>
    </div>
</div>